### ISSUE TITLE
Add a visual monitor.

### ISSUE THREAD

**Issue by mldk-tech** [Gizra-Shoov/urquidesband#1]
http://www.urquidesband.com/

**Comment by mldk-tech** [comment]
I get the error message : " Command failed: gm convert: geometry dimensions are zero (unable to crop image)"

**Comment by amitaibu** [comment]
on all pages?

**Comment by mldk-tech** [comment]
Yes

**Comment by amitaibu** [comment]
did you try to add `elem` with a specific class or ID?

**Comment by mldk-tech** [comment]
Yes, the same response

**Comment by mldk-tech** [comment]
https://app.shoov.io/#/screenshots/20917

**Comment by mldk-tech** [comment]
http://www.gfycat.com/TornDemandingDutchsmoushond

**Comment by amitaibu** [comment]
:+1:
